name: Hola Mundo en Python

on: 
  push:
    branches:
      - main

jobs:
  hola_mundo_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Ejecutar script de Hola Mundo
      run: |
        echo 'print("Hola, mundo")' > hola_mundo.py
        python hola_mundo.py
